### ISSUE TITLE
setup.sh error

### ISSUE THREAD

**Issue by CodingWithAdin** [Tastyep/Pi-OpenCast#28]
Hello,

I tried installing OpenCast and upon starting **setup.sh** I get the error:
`setup.sh: 7: setup.sh: bad substitution`
I tried removing `,,` from the 7th line I get another error
`setup.sh: 11: setup.sh: Syntax error: "(" unexpected`

Is this supposed to be run with `sudo sh setup.sh` or something else?
If I ran it correctly, how can I fix the error?

**Comment by Tastyep** [comment]
Hello,

Thank you for the issue, you are the first one, congrats!
The line was containing non-POSIX commands which I've replaced on the master branch.
You can use sudo, otherwise, the script will ask for privileges to run the commands requiring it.

Can you please tell me what operating system and bash version do you have?
If you use a non-debian / ubuntu based system you will have another error when installing the system dependencies using `apt-get`. Commenting the lines will fix the problem, the dependencies are rather common.

Also, you might be interested in checking at the develop branch which is stable and more advanced in terms of features.
If you do so, sorry in advance for the overflowing list of videos :)
 
Thank you again for your interest in the project!

**Comment by CodingWithAdin** [comment]
Hello,

I am running Raspbian Buster based on Debian 10,
Bash 5.0.3.

I have tried the develop branch, but I get the same problem,
the error seems to be in the creation of any function.
`setup.sh: 11: setup.sh: Syntax error: "(" unexpected`

I am guessing that I need to upgrade/downgrade my bash.
Thanks for the help!

**Comment by Tastyep** [comment]
Thank you for the information.
I think I got it fixed (both master and develop), you will have to pull the change and I'll wait for your feedback.
On my side, I also have Raspbian with Bash 5.0.3, but I can't reproduce the error :(. However, it seemed to be a basic syntactic error.
Hopefully, this will be your last problem.

**Comment by CodingWithAdin** [comment]
Hello,

I have tried the master branch setup.
It runs now, but gives these errors
![2020-09-06-110017_1920x1080_scrot](https://user-images.githubusercontent.com/40150678/92322411-50ed1580-f031-11ea-8287-eba30b836a59.png)
There are some errors saying that I dont have Python 3.7, I do, not sure whats that all about.
And there is apparently an error when trying to create a virtualenv.

I tried to go onto port 8081 of my Raspberry and I get the UI but when trying to play anything It just says `Error: `
No error displayed but there is apparently an error, here is a screenshot just in case
![2020-09-06-110624_1920x1080_scrot](https://user-images.githubusercontent.com/40150678/92322490-c48f2280-f031-11ea-9667-e5b9fdfcb45f.png)

What Raspberry are you using, I have a Raspberry Pi 4.
Since I upgraded from my Raspberry Pi 3 to a 4 I have noticed that 3 different casting packages will not work, even tho they worked on the 3. Im not sure how has that impacted anything.

Should I do a pull request, Im not really sure for its purpose since I havent used GitHub in a while.

**Comment by Tastyep** [comment]
Hello,

Your errors seem all to be related to the python version that is being used.
Can you run `python3 --version`? My output is `Python 3.7.3`

I strongly suggest that you switch on the develop branch (you will need to re-execute the setup script if you do so), you will benefit from the new interface (even though a problem remains).

No need for a pull request, no worries.
I run my CI on [ubuntu](https://github.com/Tastyep/Pi-OpenCast/runs/1077493755?check_suite_focus=true) and while it's not exactly the same as raspbian, it is very close. This indicates that something is different with your environment, let's find out what causes the problem.

Thank you for your time.

**Comment by Tastyep** [comment]
A preview of the new interface:
![Screenshot_2020-09-06_11-37-40](https://user-images.githubusercontent.com/3267228/92322978-2735ed80-f035-11ea-9e2f-dc218acea088.png)

**Comment by CodingWithAdin** [comment]
Hello,

My output for `python3 --version` is `Python 3.7.0`
I am trying the develop branch with ``

**Comment by CodingWithAdin** [comment]
`sudo ./setup.sh`
Sorry, dont know what happened there

**Comment by CodingWithAdin** [comment]
Hello,

I have tried the develop branch with `sudo /setup.sh`
It gives me the same errors for python and for trying to create a virtualenv

**Comment by CodingWithAdin** [comment]
The UI Appears, but trying to cast doesnt do anything

**Comment by CodingWithAdin** [comment]
Is there any logs I would be able to send you?

**Comment by Tastyep** [comment]
Ok I found the issue, do not execute the setup script using sudo, just do `./setup.sh`

The setup instruction in the README file on develop had been updated to be clearer, so I can understand how you ran into this:
![Screenshot_2020-09-06_11-55-26](https://user-images.githubusercontent.com/3267228/92323267-a3313500-f037-11ea-8b85-dd64f019670b.png)

Also, since there is no immediate feedback on the interface you can tail the logs of the service, to do so:
`./OpenCast.sh service back log`

**Comment by CodingWithAdin** [comment]
Alright, trying it now. If there is an error I will send you the log
Also, shouldnt it be
`git clone --branch develop https://github.com/Tastyep/Pi-OpenCast.git` for the develop branch

**Comment by Tastyep** [comment]
Since I do my releases on master it is not necessary, the releases should be stable while the develop branch doesn't guarantee it.
However with the way it's been I consider the develop branch to be more stable as more tested (thanks to Github actions) 
Normally I expect to be a few days away from fixing that last problem on the interface and making a new release.

**Comment by CodingWithAdin** [comment]
![2020-09-06-122433_1920x1080_scrot](https://user-images.githubusercontent.com/40150678/92323803-eee5dd80-f03b-11ea-8dbf-5189a98d96fe.png)
Logs not found,
When Installing the same error remains for the virtualenv.
UI Still works, but gives no response

**Comment by Tastyep** [comment]
As long as the setup fails the service won't start which explains why you don't have logs.
Can you please provide a complete screenshot of the setup logs when doing `./setup.sh`?

**Comment by CodingWithAdin** [comment]
Hello, the setup log remains the same
https://user-images.githubusercontent.com/40150678/92322411-50ed1580-f031-11ea-8287-eba30b836a59.png

**Comment by Tastyep** [comment]
I may have some hints about why this happens, can you run
`source ~/.profile; poetry env use 3.7`
I expect that you get the same error.
This [issue](https://github.com/python-poetry/poetry/issues/2711) seems to be related to your problem.
Also, can you provide the version of poetry causing the issue ? `poetry --version`
Maybe running `poetry self update --preview` could help you,  if you do so, try again running `poetry env use 3.7` and see if the problem persists.
If this works, comment `install_system_deps` in `setup.sh` and try running it again.

**Comment by Tastyep** [comment]
I've reinstalled Opencast on my rPi and don't have the issue, so I expect you not to have it too.
Again, can you run the setup script `./setup.sh` and provide a screenshot ?

The log should contain some differences.
What I'm looking at especially is the Runtime warning (above the brown colored line), while not important (I have it too), it shows where poetry is installed. If it is installed as root: /root/.poetry/... then the setup will fail, I was able to reproduce this when running `sudo ./setup.sh`

**Comment by Tastyep** [comment]
I forgot to remove the virtualenv while reinstalling ... then ran into the same problem as you.
`poetry self update --preview` worked for me, I hope it did for you too.
It is bad luck because [Poetry](https://github.com/python-poetry/poetry) is a very good tool.

Please tell me if you managed to set up the application so I can close this issue.

**Comment by CodingWithAdin** [comment]
Hello,

Sorry for the late reply, that fixes it.
Thanks.
